version: "3.7"

services:
  backend:
    build:
      context: ./ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    volumes:
      - "./model:/src/model"
    depends_on:
      - training

  frontend:
    build:
      context: ./ml-kurkkumopo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  training:
    build:
      context: ./ml-kurkkumopo-training
    volumes:
      - "./model:/src/model"
      - "./imgs:/src/imgs"
